name: Build and deploy ASP.Net Core app to Azure Web App - StudentPerformanceAPIGateway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0' # Update to the correct .NET version

      - name: Build with dotnet
        run: dotnet build --configuration Release StudentPerformanceAPIGateway/StudentPerformanceAPIGateway.csproj

      - name: dotnet publish
        run: dotnet publish StudentPerformanceAPIGateway/StudentPerformanceAPIGateway.csproj -c Release -o ${{github.workspace}}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'StudentPerformanceAPIGateway'
          slot-name: 'Production'
          package: ${{github.workspace}}/publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_06E12B0C5FA549088E0A64FF62C223D9 }}
